function [mnaopt] = ocelectric(GlobalSamplingFrequency, args)
arguments
    GlobalSamplingFrequency (1,1) Frequency = Frequency(200, 'kHz');
    args.Numstacks (1,1) double = 600;
    args.mna_ver (1,:) char = 'dev2'
    args.plotopt (1,:) plotOpt = plotOpt('MNA');
end

mnaopt = mnaOpt( ...
    ...'capacitance_state_dependence', 'none', ...
    ...'capacitance_state_dependence', 'weak', ...
    'capacitance_state_dependence', 'strong', ...
    ...
    ...'zero_capacitance_test', true, ...
    ...
    ...'IHC_basolateral_conductance_dependance', 'none', ...
    ...'IHC_basolateral_conductance_dependance', 'vihc', ...
    ...'IHC_basolateral_conductance_dependance', 'vihc_ss', ...
    ...'IHC_basolateral_conductance_dependance', 'channel_popen', ...
    'IHC_basolateral_conductance_dependance', 'channel_popen_tonotopic', ...
    ...
    ...'OHC_basolateral_conductance_dependance', 'none', ...
    ...'OHC_basolateral_conductance_dependance', 'vohc', ...
    ...'OHC_basolateral_conductance_dependance', 'vohc_ss', ...
    'OHC_basolateral_conductance_dependance', 'channel_popen', ...
    ...
    'IHC_MET_dependence', 'BM', ...
    'OHC_MET_dependence', 'cilia', ...
    ...
    'Numstacks', args.Numstacks, ...
    'NumDiv', 'auto', ...
    'solver', 'ode15s', ...
    'fallback_solver', 'ode23t', ...
    'save_method', ...
        'matlab_matfile', ...
        ...'c_posix', ...
    'evalAtTimePoints', true, ...
    'solveropt', {{ ...
        ...'RelTol', 5e-2, ...
        ...'RelTol', 1e-6, ...
        'RelTol', 1e-9, ...
        ...'RelTol', 1e-4, ...
        ...'RelTol', 1e-5, ...
        }}, ...
    'add_solveropt', struct( ...
        'use_jacobian', true, ...
        'use_jpattern', false), ...
    'samplingFrequency', GlobalSamplingFrequency ...
    );

[mnaopt] = devopts.ocelectric_templates(mnaopt, "mna_ver", args.mna_ver);

end