function [FP] = fiber_properties_0522()
%FIBER_PROPERTIES_0522 

FP = [];

FP.test_1 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(10/4, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3/4, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f1' ...
        ), ...
};

FP.test_2 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(10/4, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3/4, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ... 
        'DisplayName', 'f2' ...
        ), ...
};

FP.test_3 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290, 'Hz'), ...% loss rate
        'x', Frequency(66.3, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(16*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(16*100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f3' ...
        ), ...
};

FP.test_4 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(4*10, 'Hz'), ...% manufacture rate
        'l', Frequency(4*1290, 'Hz'), ...% loss rate
        'x', Frequency(4*66.3, 'Hz'), ...% reprocessing rate
        'r', Frequency(4*3290, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(16*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(16*100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f4' ...
        ), ...
};

FP.test_5 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'num_CaV13', 2*72, ...
        'y', Frequency(10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290, 'Hz'), ...% loss rate
        'x', Frequency(66.3, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f5' ...
        ), ...
};

FP.test_6 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(4*10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3/4, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f6' ...
        ), ...
};

FP.test_6_n4 = FP.test_6;
FP.test_6_n4{1}.DisplayName = 'f6_n4';
FP.test_6_n4{1}.num_inactive_release_sites = 14 - 4;
FAC = 14/4;
FP.test_12_n4{1}.transmitter_release_parameters = struct( ...
    'apex', {{ ...
        Frequency(FAC*4*100, 'Hz'), ...
        5.0, ...      % Hill's coefficient
        80e-6}}, ... % Half activation [Ca2+ M]
    'base', {{ ...
        Frequency(FAC*4*100, 'Hz'), ...
        5.0, ...
        80e-6}} ...
    );

FP.test_6b = {
    struct( ...
        'num_vesicles', 4, ...
        'num_CaV13', 72/2, ...
        'y', Frequency(4*10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3/4, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f6b' ...
        ), ...
};

FP.test_7 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(4*10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(4*66.3, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f7' ...
        ), ...
};

FP.test_8 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(8*10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f8' ...
        ), ...
};

FP.test_9 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(8*10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    100e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    100e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f9' ...
        ), ...
};

FP.test_10 = {
    struct( ...
        'num_vesicles', 4, ...
        'num_CaV13', 72/2, ...
        'y', Frequency(8*10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    100e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    100e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f10' ...
        ), ...
};

FP.test_11 = {
    struct( ...
        'num_vesicles', 4, ...
        'num_CaV13', 72, ...
        'y', Frequency(8*10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    100e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    100e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f11' ...
        ), ...
};

FP.test_12 = {
    struct( ...
        ...'num_vesicles', 28, ...
        'y', Frequency(10, 'Hz'), ...% manufacture rate
        'l', Frequency(1290/4, 'Hz'), ...% loss rate
        'x', Frequency(66.3/4, 'Hz'), ...% reprocessing rate
        'r', Frequency(3290/4, 'Hz'), ...% re-uptake rate
        'transmitter_release_parameters', ...
            struct( ...
                'apex', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...      % Hill's coefficient
                    80e-6}}, ... % Half activation [Ca2+ M]
                'base', {{ ...
                    Frequency(4*100, 'Hz'), ...
                    5.0, ...
                    80e-6}} ...
            ), ...
        'SR', 'ring_variable_2', ...
        'DisplayName', 'f12' ...
        ), ...
};


FP.test_12_n4 = FP.test_12;
FP.test_12_n4{1}.DisplayName = 'f12_n4';
FP.test_12_n4{1}.num_inactive_release_sites = 14 - 4;
FAC = 14/4;
FP.test_12_n4{1}.transmitter_release_parameters = struct( ...
    'apex', {{ ...
        Frequency(FAC*4*100, 'Hz'), ...
        5.0, ...      % Hill's coefficient
        80e-6}}, ... % Half activation [Ca2+ M]
    'base', {{ ...
        Frequency(FAC*4*100, 'Hz'), ...
        5.0, ...
        80e-6}} ...
    );

end

